export const stepperOccupationOptions = [
  { label: 'Graphic designer', value: 'graphic-designer' },
  { label: 'Consultant', value: 'consultant' },
  { label: 'Online seller', value: 'online-seller' },
  { label: 'Healthcare professional', value: 'healthcare-professional' },
  { label: 'Real estate agent', value: 'real-estate-agent' },
  { label: 'Web developer', value: 'web-developer' },
  { label: 'Software engineer', value: 'software-engineer' },
  { label: 'Content writer', value: 'content-writer' },
  { label: 'Digital marketer', value: 'digital-marketer' },
  { label: 'Social media manager', value: 'social-media-manager' },
  { label: 'Photographer', value: 'photographer' },
  { label: 'Videographer', value: 'videographer' },
  { label: 'Video editor', value: 'video-editor' },
  { label: 'Translator', value: 'translator' },
  { label: 'Virtual assistant', value: 'virtual-assistant' },
  { label: 'Accountant', value: 'accountant' },
  { label: 'Bookkeeper', value: 'bookkeeper' },
  { label: 'Tax preparer', value: 'tax-preparer' },
  { label: 'Attorney', value: 'attorney' },
  { label: 'Legal consultant', value: 'legal-consultant' },
  { label: 'Tutor', value: 'tutor' },
  { label: 'Online teacher', value: 'online-teacher' },
  { label: 'Course creator', value: 'course-creator' },
  { label: 'Personal trainer', value: 'personal-trainer' },
  { label: 'Fitness instructor', value: 'fitness-instructor' },
  { label: 'Nutritionist', value: 'nutritionist' },
  { label: 'Life coach', value: 'life-coach' },
  { label: 'Business coach', value: 'business-coach' },
  { label: 'Career coach', value: 'career-coach' },
  { label: 'UI/UX designer', value: 'ui-ux-designer' },
  { label: 'Interior designer', value: 'interior-designer' },
  { label: 'Architect', value: 'architect' },
  { label: 'Event planner', value: 'event-planner' },
  { label: 'Wedding planner', value: 'wedding-planner' },
  { label: 'Travel agent', value: 'travel-agent' },
  { label: 'Tour guide', value: 'tour-guide' },
  { label: 'Musician', value: 'musician' },
  { label: 'Music producer', value: 'music-producer' },
  { label: 'Voice actor', value: 'voice-actor' },
  { label: 'Podcaster', value: 'podcaster' },
  { label: 'Blogger', value: 'blogger' },
  { label: 'YouTuber', value: 'youtuber' },
  { label: 'Influencer', value: 'influencer' },
  { label: 'Chef', value: 'chef' },
  { label: 'Caterer', value: 'caterer' },
  { label: 'Baker', value: 'baker' },
  { label: 'Tailor', value: 'tailor' },
  { label: 'Fashion designer', value: 'fashion-designer' },
  { label: 'Jewelry maker', value: 'jewelry-maker' },
  { label: 'Carpenter', value: 'carpenter' },
  { label: 'Electrician', value: 'electrician' },
  { label: 'Plumber', value: 'plumber' },
  { label: 'Handyman', value: 'handyman' },
  { label: 'Landscaper', value: 'landscaper' },
  { label: 'Gardener', value: 'gardener' },
  { label: 'House cleaner', value: 'house-cleaner' },
  { label: 'Dog walker', value: 'dog-walker' },
  { label: 'Pet sitter', value: 'pet-sitter' },
  { label: 'Veterinarian', value: 'veterinarian' },
  { label: 'Childcare provider', value: 'childcare-provider' },
  { label: 'Elderly caregiver', value: 'elderly-caregiver' },
  { label: 'Massage therapist', value: 'massage-therapist' },
  { label: 'Psychologist', value: 'psychologist' },
  { label: 'Therapist', value: 'therapist' },
  { label: 'Counselor', value: 'counselor' },
  { label: 'Project manager', value: 'project-manager' },
  { label: 'Product manager', value: 'product-manager' },
  { label: 'Operations manager', value: 'operations-manager' },
  { label: 'HR consultant', value: 'hr-consultant' },
  { label: 'Recruiter', value: 'recruiter' },
  { label: 'Data analyst', value: 'data-analyst' },
  { label: 'Data scientist', value: 'data-scientist' },
  { label: 'Business analyst', value: 'business-analyst' },
  { label: 'Financial advisor', value: 'financial-advisor' },
  { label: 'Investment consultant', value: 'investment-consultant' },
  { label: 'Insurance agent', value: 'insurance-agent' },
  { label: 'Mortgage broker', value: 'mortgage-broker' },
  { label: 'SEO specialist', value: 'seo-specialist' },
  { label: 'PPC specialist', value: 'ppc-specialist' },
  { label: 'Email marketer', value: 'email-marketer' },
  { label: 'Copywriter', value: 'copywriter' },
  { label: 'Technical writer', value: 'technical-writer' },
  { label: 'Ghostwriter', value: 'ghostwriter' },
  { label: 'Editor', value: 'editor' },
  { label: 'Proofreader', value: 'proofreader' },
  { label: 'Transcriptionist', value: 'transcriptionist' },
  { label: 'Medical transcriptionist', value: 'medical-transcriptionist' },
  { label: 'Court reporter', value: 'court-reporter' },
  { label: 'Researcher', value: 'researcher' },
  { label: 'Academic writer', value: 'academic-writer' },
  { label: 'Grant writer', value: 'grant-writer' },
  { label: 'Fundraiser', value: 'fundraiser' },
  { label: 'Nonprofit consultant', value: 'nonprofit-consultant' },
  {
    label: 'Public relations specialist',
    value: 'public-relations-specialist',
  },
  { label: 'Brand strategist', value: 'brand-strategist' },
  { label: 'Advertising specialist', value: 'advertising-specialist' },
  { label: 'Market researcher', value: 'market-researcher' },
  { label: 'App developer', value: 'app-developer' },
  { label: 'Mobile developer', value: 'mobile-developer' },
  { label: 'Game developer', value: 'game-developer' },
  { label: 'Blockchain developer', value: 'blockchain-developer' },
  { label: 'AI specialist', value: 'ai-specialist' },
  { label: 'Cybersecurity specialist', value: 'cybersecurity-specialist' },
  { label: 'Network administrator', value: 'network-administrator' },
  { label: 'Systems analyst', value: 'systems-analyst' },
  { label: 'DevOps engineer', value: 'devops-engineer' },
  { label: 'QA tester', value: 'qa-tester' },
  { label: '3D modeler', value: '3d-modeler' },
  { label: 'Animator', value: 'animator' },
  { label: 'Illustrator', value: 'illustrator' },
  { label: 'Motion graphics artist', value: 'motion-graphics-artist' },
  { label: 'Print designer', value: 'print-designer' },
  { label: 'Packaging designer', value: 'packaging-designer' },
  { label: 'Logo designer', value: 'logo-designer' },
  { label: 'Tattoo artist', value: 'tattoo-artist' },
  { label: 'Makeup artist', value: 'makeup-artist' },
  { label: 'Hair stylist', value: 'hair-stylist' },
  { label: 'Esthetician', value: 'esthetician' },
  { label: 'Personal shopper', value: 'personal-shopper' },
  { label: 'Stylist', value: 'stylist' },
  { label: 'Doula', value: 'doula' },
  { label: 'Midwife', value: 'midwife' },
  { label: 'Nurse', value: 'nurse' },
  { label: 'Dentist', value: 'dentist' },
  { label: 'Dental hygienist', value: 'dental-hygienist' },
  { label: 'Optometrist', value: 'optometrist' },
  { label: 'Chiropractor', value: 'chiropractor' },
  { label: 'Acupuncturist', value: 'acupuncturist' },
  { label: 'Physical therapist', value: 'physical-therapist' },
  { label: 'Occupational therapist', value: 'occupational-therapist' },
  { label: 'Speech therapist', value: 'speech-therapist' },
  { label: 'Dietitian', value: 'dietitian' },
  { label: 'Pharmacist', value: 'pharmacist' },
  { label: 'Home inspector', value: 'home-inspector' },
  { label: 'Property manager', value: 'property-manager' },
  { label: 'Construction contractor', value: 'construction-contractor' },
  { label: 'Interior decorator', value: 'interior-decorator' },
  { label: 'Home stager', value: 'home-stager' },
  { label: 'Mover', value: 'mover' },
  { label: 'Driver', value: 'driver' },
  { label: 'Delivery courier', value: 'delivery-courier' },
  { label: 'Truck driver', value: 'truck-driver' },
  { label: 'Fleet manager', value: 'fleet-manager' },
  { label: 'Logistics coordinator', value: 'logistics-coordinator' },
  { label: 'Warehouse manager', value: 'warehouse-manager' },
  { label: 'Import/export specialist', value: 'import-export-specialist' },
  { label: 'Customs broker', value: 'customs-broker' },
  { label: 'Farmer', value: 'farmer' },
  { label: 'Florist', value: 'florist' },
  { label: 'Beekeeper', value: 'beekeeper' },
  { label: 'Vintner', value: 'vintner' },
  { label: 'Brewer', value: 'brewer' },
  { label: 'Distiller', value: 'distiller' },
  { label: 'Craftsperson', value: 'craftsperson' },
  { label: 'Artist', value: 'artist' },
  { label: 'Artisan', value: 'artisan' },
  { label: 'Printmaker', value: 'printmaker' },
  { label: 'Sculptor', value: 'sculptor' },
  { label: 'Woodworker', value: 'woodworker' },
  { label: 'Metalworker', value: 'metalworker' },
  { label: 'Glassblower', value: 'glassblower' },
  { label: 'Potter', value: 'potter' },
  { label: 'Weaver', value: 'weaver' },
  { label: 'Knitter', value: 'knitter' },
  { label: 'Seamstress', value: 'seamstress' },
  { label: 'Upholsterer', value: 'upholsterer' },
  { label: 'Antique dealer', value: 'antique-dealer' },
  { label: 'Auctioneer', value: 'auctioneer' },
  { label: 'Appraiser', value: 'appraiser' },
  { label: 'Tour operator', value: 'tour-operator' },
  { label: 'Interpreter', value: 'interpreter' },
  { label: 'Language teacher', value: 'language-teacher' },
  { label: 'Flight instructor', value: 'flight-instructor' },
  { label: 'Ski instructor', value: 'ski-instructor' },
  { label: 'Scuba instructor', value: 'scuba-instructor' },
  { label: 'Swimming coach', value: 'swimming-coach' },
  { label: 'Sports coach', value: 'sports-coach' },
  { label: 'Esports coach', value: 'esports-coach' },
  { label: 'Chess teacher', value: 'chess-teacher' },
  { label: 'Music teacher', value: 'music-teacher' },
  { label: 'Dance instructor', value: 'dance-instructor' },
  { label: 'Acting coach', value: 'acting-coach' },
  { label: 'Public speaking coach', value: 'public-speaking-coach' },
];
