import {
  Lightbulb,
  MonitorPlay,
  Wifi,
  Bus,
  ParkingCircle,
  Dog,
  Phone,
  Briefcase,
  Train,
  RotateCcw,
  PiggyBank,
  Car,
  MonitorSmartphone,
  Database,
  School,
  Box,
  Receipt,
  ArrowRightLeft,
  Megaphone,
  ShieldCheck,
  Landmark,
  Laptop,
  Wrench,
  CarTaxiFront,
  Baby,
  Shirt,
  Coffee,
  Fuel,
  Gift,
  Building,
  Leaf,
  ShoppingCart,
  HeartPulse,
  DollarSign,
  GraduationCap,
  Shield,
  Heart,
  BanknoteIcon,
  UtensilsCrossed,
  Stethoscope,
  Home,
  Music,
  Building2,
  CarFront,
  HelpCircle,
  Users,
  Package,
  CreditCard,
  Ticket,
  CalendarCheck,
  Plane,
  Dice1,
  Wallet,
  Hotel,
  FileText,
  Coins,
  BookOpen,
  Plug,
  Scissors,
} from 'lucide-react';

const categoryIconMap = {
  'Travel lodging': Hotel,
  Utilities: Lightbulb,
  'Video streaming': MonitorPlay,
  'Wifi bill': Wifi,
  'Other transport': Bus,
  Parking: ParkingCircle,
  Payroll: Receipt,
  'Personal care': Scissors,
  'Pet supplies': Dog,
  'Phone bill': Phone,
  'Professional service': Briefcase,
  'Public transport': Train,
  Refund: RotateCcw,
  Rent: Home,
  'Rental / home insurance': Shield,
  'Retirement transfer': PiggyBank,
  Ride: CarTaxiFront,
  Shipping: Package,
  Software: MonitorSmartphone,
  Storage: Database,
  'Student loan': GraduationCap,
  'Student tuition': School,
  Supplies: Box,
  'Tax payment': FileText,
  'Toll fee': Landmark,
  Transfer: ArrowRightLeft,
  Advertising: Megaphone,
  'Bank fee': Landmark,
  'Business insurance': ShieldCheck,
  'Business license': FileText,
  'Capital expense': Coins,
  'Car insurance': ShieldCheck,
  'Car loan payment': BanknoteIcon,
  'Car maintenance': Wrench,
  'Car rental': CarTaxiFront,
  'Car wash': Car,
  Charity: Heart,
  'Child adoption': Baby,
  'Child care': Baby,
  Clothing: Shirt,
  'Coffee shop': Coffee,
  Gambling: Dice1,
  'Gas fill up': Fuel,
  Gift: Gift,
  Government: Building,
  'Green home improvement': Leaf,
  Groceries: ShoppingCart,
  'Health insurance': HeartPulse,
  'Home office expense': Laptop,
  'HSA transfer': BanknoteIcon,
  Income: DollarSign,
  'Industry education': BookOpen,
  Insurance: Shield,
  'Investment transfer': Wallet,
  'Life insurance': Heart,
  'Loan payment': BanknoteIcon,
  Meal: UtensilsCrossed,
  'Medical expense': Stethoscope,
  Mortgage: Home,
  'Music streaming': Music,
  'Office space': Building2,
  'Other car expense': CarFront,
  'Other expense': HelpCircle,
  'Contractor payment': Users,
  'Cost of goods sold': Package,
  'Credit card payment': CreditCard,
  Entertainment: Ticket,
  'EV charging': Plug,
  Event: CalendarCheck,
  Flight: Plane,
};

export const getCategoryIcon = (category: string) => {
  return (
    categoryIconMap[category as keyof typeof categoryIconMap] || HelpCircle
  );
};
